name: Example
version: '1.0-SNAPSHOT'
main: it.alzy.examplePlugin.Example
api-version: '1.21'
depends: ['SimpleEconomy']
commands:
  example:
    description: An example command
    usage: /<command>
